### ISSUE TITLE
Importing my Bookmarks Successful, but shows no bookmarks

### ISSUE THREAD

**Issue by jlar0che** [haishanh/cherry#23]
I've installed Cherry version 0.0.6  and it is working flawlessly, but after importing my bookmarks no bookmarks are shown.

My bookmarks HTML backup file is 10.8 megabytes in size. The newest versions of Firefox (version 108.0.1) and Google Chrome (version 108.0.5359.125) both successfully import my bookmarks file. But, Pocket does not -- it does the same thing Cherry does (shows 0 bookmarks after "successfully" importing my bookmarks backup file).

Perhaps the issue has something to do with my bookmark file as I've been faithfully backing up my bookmarks since 2007?

A copy of my Bookmarks file can be found [here](https://massarchive.home-lab.site/sharing/kBTUvxCJn).

**Comment by haishanh** [comment]
Sorry for replying so late. It seems I can import the bookmark file without an issue, 4601 items imported. The file is quite large due to it contains lots of base64'd favicons.
(The link to the bookmark file seems expired, luckily I downloaded it earlier. I was planing to look into the issue last time but end up don't have enough time.)
